<!-- FreeFind search form START -->
                <form class="ff3" action="http://search.freefind.com/find.html" style="margin: 20px 0 20px 0;"
                      method="get" accept-charset="utf-8"
                      id="FreeFindForm">
                  <p style="text-align:center;margin:0;padding:0">
                      <input type="hidden" name="id"        value="82328757" />
                      <input type="hidden" name="pageid"    value="r" />
                      <input type="hidden" name="mode"      value="ALL" />
                      <input type="hidden" name="n"         value="0" />
                      <input type="hidden" name="_charset_" value="" />
                      <input type="hidden" name="bcd"       value="÷" />
                      <input type="text" class="ff1" style="width:120px;color:black;background-color:white" name="query" id="query" size="10" />
                      <input type="submit" class="ff2" value="Search" />
                  </p>
                </form>
                <!-- FreeFind search form END -->
