
                <!-- Begin: Insert Google map of articles -->
                <table border="1">
                    <tr><td>
                        <div id="map" style="width: 780px; height: 520px"></div>
                    </td></tr><tr><td>
                        <div id="selection"></div>
                    </td></tr><tr><td style="vertical-align: top">
                        <div id="side_bar"></div>
                    </td></tr>
                </table>
                <!-- End: Insert Google map of articles -->
