
        <!-- geo tags for {{geo_address}} -->
        <meta name="ICBM"                       content="{{geo_lat}}, {{geo_lon}}" />

        <meta name="geo.country"                content="{{geo_country_code}}" />
        <meta name="geo.region"                 content="{{geo_region}}" />
        <meta name="geo.position"               content="{{geo_lat}}; {{geo_lon}}" />
        <meta name="geo.placename"              content="{{geo_placename_strip}}" />
        <!--                                                      -->
        <!-- originally written in V2, needs to be upgraded to V3 -->
        <!--                                                      -->
